modelFilePath: "api-generation/library/library.xml"
modelConfig:
  packageNames:
    typesPackage: "library"
    queriesPackage: "interfaces"
  defaults:
    classDefaults:
      classActions:
        - CREATE
        - READ
      highInstanceCount: false
      implementNode: true
      immutable: false
dependencies:
  "Personal Details":
    modelFilePath: "api-generation/personal-details/${MTT_MODEL_FILE}"
    version: "1.0.0"
  "Core Types":
    modelFilePath: "api-generation/core-types/${MTT_MODEL_FILE}"
    version: "1.0.0"
loader:
  loaderURL: "http://localhost:7010"
  configFilePath: "api-generation/common-config/config/loaders/ea-xmi/config.yaml"
generators:
  aoco:
    generatorURL: "http://localhost:9015"
    configFilePath: "api-generation/common-config/config/generators/aoco/config.yaml"
  elastic-mapper":
    generatorURL: "http://localhost:9005"
    configFilePath: "api-generation/common-config/config/generators/elastic-mapper/config.yaml"
  graphql:
    generatorURL: "http://localhost:9025"
    configFilePath: "api-generation/common-config/config/generators/graphql/config.yaml"
  mk-docs:
    generatorURL: "http://localhost:9020"
    configFilePath: "api-generation/common-config/config/generators/mkdoc/config.yaml"
  openapi:
    generatorURL: "http://localhost:9010"
    configFilePath: "api-generation/common-config/config/generators/openapi/config.yaml"
  protobuf:
    generatorURL: "http://localhost:9045"
    configFilePath: "api-generation/common-config/config/generators/protobuf/config.yaml"
  canonical:
    generatorURL: "http://localhost:9050"
    configFilePath: "api-generation/common-config/config/generators/canonical/config.yaml"
  reversed:
    generatorURL: "http://localhost:9035"
    configFilePath: "api-generation/common-config/config/generators/reversed/config.yaml"
